{
 "title": "vLLM-New",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_e2e_request_latency_seconds_bucket",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "(openmetrics.prometheus.vllm_e2e_request_latency_seconds_sum) / (openmetrics.prometheus.vllm_e2e_request_latency_seconds_count)\n",
     "legendFormat": "Average",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_generation_tokens_total",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Time Per Output Token Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_time_per_output_token_seconds_bucket",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.prometheus.vllm_time_per_output_token_seconds_sum",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_num_requests_running",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.prometheus.vllm_num_requests_swapped",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.prometheus.vllm_num_requests_waiting",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Time to First Token Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_time_to_first_token_seconds_bucket",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_gpu_cache_usage_perc",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.prometheus.vllm_cpu_cache_usage_perc",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_request_prompt_tokens_bucket",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_request_generation_tokens_bucket",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_request_success_total",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_request_queue_time_seconds_sum",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Requests Prefill and Decode Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_request_prefill_time_seconds_sum",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    },
    {
     "expr": "openmetrics.prometheus.vllm_request_decode_time_seconds_sum",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  },
  {
   "title": "Max Generation Token in Sequence Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "openmetrics.prometheus.vllm_request_max_num_generation_tokens_sum",
     "options": {
      "rateConversion": true,
      "timeUtilizationConversion": true
     }
    }
   ]
  }
 ]
}