apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-llama-serve-monitor
  namespace: llama-serve
spec:
  namespaceSelector: {}
  podMetricsEndpoints:
    - bearerTokenSecret:
        key: ''
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: vllm        # Must match the pod labels
