apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: vllm-llama-serve
  namespace: llama-serve
spec:
  selector:
    matchLabels:
      app: vllm        # Must match the Service labels
  endpoints:
  - port: "8000"      # Must match the Service port name
    path: /metrics     # Path to your metrics endpoint
    interval: 5s
