apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-hub
resources:
- grafana-instance.yaml
- role.yaml
- route.yaml
- datasources.yaml
# need to create token secret separate to ensure grafana-sa exists first
# - sa-token-secret.yaml

