apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: observability-hub
resources:
- tempo-role.yaml
- minio-secret-tempo.yaml
- minio-tempo-pvc.yaml
- minio-tempo-svc.yaml
- minio-tempo.yaml
- tempo-multitenant.yaml
