# based on config/samples/openshift/tempo_v1alpha1_multitenancy.yaml
apiVersion: tempo.grafana.com/v1alpha1
kind:  TempoStack
metadata:
  name: tempostack
spec:
  storage:
    secret:
      name: minio-tempo
      type: s3
  storageSize: 15Gi
  resources:
    total:
      limits:
        memory: 10Gi
        cpu: 5000m
  tenants:
    mode: openshift
    authentication:
      - tenantName: dev
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa"
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true
