apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llama-stack
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  #- otel-collector-sidecar.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: run-config
    files:
      - run.yaml
