kind: OpenTelemetryCollector
metadata:
  name: llamastack-otel-collector
  namespace: llama-stack
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      batch: {}

    exporters:
      logging:
        loglevel: debug

      otlp/tempo:
        endpoint: http://tempo.llm-d-monitoring.svc.cluster.local:4317 # <- Update llm-d-monitoring to the ns running tempo if different
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/tempo]
