apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: llamastack-otel-collector
  namespace: llama-stack
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      
      otlp/tempo:
        endpoint: http://tempo.llm-d-monitoring.svc.cluster.local:3100
        tls:
          insecure: true
      
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/tempo] 
