# Once this exists, any pod with the template.metadata.annotation below will send metrics
# sidecar.opentelemetry.io/inject: llamastack-otelsidecar
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: llamastack-otelsidecar
spec:
  mode: sidecar
  config:
    exporters:
      debug: {}
      otlp/tempo:
        endpoint: http://tempo.llm-d-monitoring.svc.cluster.local:4317 # <- Update llm-d-monitoring to the ns running tempo if different
        tls:
          insecure: true
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    service:
      pipelines:
        traces:
          exporters:
            - debug
            - otlp/tempo
          receivers:
            - otlp
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/tempo]
