apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: llamastack-otelsidecar
  namespace: llama-stack
spec:
  args:
    feature-gates: -component.UseLocalHostAsDefaultHost
  config:
    exporters:
      debug:
        verbosity: detailed
      otlp/tracing:
        endpoint: http://tempo.tracing.svc.cluster.local:4317
        tls:
          insecure: true
    processors:
      batch: {}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        traces:
          exporters:
          - debug
          - otlp/tracing
          processors:
          - batch
          receivers:
          - otlp
  mode: sidecar
