apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llamastack-data
  namespace: llama-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Use minikube's default storage class 