apiVersion: v1
kind: Service
metadata:
  name: llamastack
  namespace: llama-stack
  labels:
    app: llamastack
spec:
  type: NodePort
  ports:
  - port: 8321
    targetPort: 8321
    protocol: TCP
    name: http
    nodePort: 30321  # Accessible via minikube IP:30321
  selector:
    app: llamastack 
